### ISSUE TITLE
Add simplest question parsing technique

### ISSUE THREAD

**Issue by MauricioCarmelo** [MauricioCarmelo/QuestionAnsweringSystem#1]
Gerar uma query que será usada como entrada para a etapa de Information Retrieval.

## Passos 
* Quebrar a frase em palavras
* Remover stop words

## Detalhes:

Remover stop words
	
Verificar as seguintes bibliotecas:
* spacy (https://spacy.io/ - ingles e portugues)
* nltk - ver se dá pra gerar token também
```
import nltk
from nltk.corpus import stopwords
set(stopwords.words('english'))
```
Essas palavras serão usadas como query de busca para a próxima etapa.

**Comment by eduardogc8** [comment]
O nltk tem uma função para quebrar o texto em tokens.
```
import nltk
sentence = """At eight o'clock on Thursday morning Arthur didn't feel very good."""
tokens = nltk.word_tokenize(sentence)
tokens
['At', 'eight', "o'clock", 'on', 'Thursday', 'morning',
'Arthur', 'did', "n't", 'feel', 'very', 'good', '.']
```

**Comment by MauricioCarmelo** [comment]
Implementado na Pull Request **Adding simple split question parsing [feature] #3**
